"""Archivist agent: produces CODEBASE.md, onboarding_brief, lineage, trace."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from ..graph.knowledge_graph import KnowledgeGraph
from ..models import DayOneAnswer, DatasetNode, ModuleNode
from ..storage import get_cartography_dir


def _serialize_default(obj: Any) -> Any:
    if hasattr(obj, "isoformat"):
        return obj.isoformat()
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")


class ArchivistAgent:
    """Produces and maintains cartography artifacts for human/AI consumption."""

    def run(
        self,
        repo_root: Path,
        graph: KnowledgeGraph,
        modules: Dict[str, ModuleNode],
        datasets: Dict[str, DatasetNode],
        day_one_answers: Dict[str, DayOneAnswer],
        traces: List[Dict[str, Any]],
    ) -> None:
        cart = get_cartography_dir(repo_root)
        cart.mkdir(parents=True, exist_ok=True)

        self._write_codebase_md(cart / "CODEBASE.md", graph, modules, datasets)
        self._write_onboarding_brief(cart / "onboarding_brief.md", day_one_answers)
        self._write_lineage_graph(cart / "lineage_graph.json", graph)
        self._append_trace(cart / "cartography_trace.jsonl", traces)

    def _write_codebase_md(
        self,
        path: Path,
        graph: KnowledgeGraph,
        modules: Dict[str, ModuleNode],
        datasets: Dict[str, DatasetNode],
    ) -> None:
        lines: List[str] = [
            "# Codebase Architecture Overview",
            "",
            "## Architecture Overview",
            "This document is auto-generated by the Brownfield Cartographer for AI agent injection.",
            "",
        ]
        # Critical path (top 5 by PageRank)
        try:
            pr = graph.pagerank()
            top = sorted(pr.items(), key=lambda x: x[1], reverse=True)[:5]
            lines.append("## Critical Path (Top 5 by PageRank)")
            for node, score in top:
                mod = modules.get(node)
                if mod:
                    lines.append(f"- `{node}` (score={score:.4f}, velocity={mod.change_velocity_30d})")
            lines.append("")
        except Exception:
            pass
        # Data sources & sinks
        lines.append("## Data Sources & Sinks")
        sources = list(graph.find_sources())
        sinks = list(graph.find_sinks())
        lines.append("### Sources (entry points)")
        for s in sources[:20]:
            lines.append(f"- `{s}`")
        lines.append("### Sinks (exit points)")
        for s in sinks[:20]:
            lines.append(f"- `{s}`")
        lines.append("")
        # Known debt
        lines.append("## Known Debt")
        dead = [m for m in modules.values() if m.is_dead_code_candidate]
        lines.append(f"- Dead code candidates: {len(dead)}")
        for m in dead[:10]:
            lines.append(f"  - `{m.path}`")
        try:
            sccs = list(graph.strongly_connected_components())
            cycles = [s for s in sccs if len(s) > 1]
            lines.append(f"- Circular dependency clusters: {len(cycles)}")
            for c in cycles[:3]:
                lines.append(f"  - {list(c)[:5]}...")
        except Exception:
            pass
        lines.append("")
        # High-velocity files
        lines.append("## High-Velocity Files (last 30 days)")
        by_vel = sorted(modules.values(), key=lambda m: m.change_velocity_30d, reverse=True)[:15]
        for m in by_vel:
            if m.change_velocity_30d > 0:
                lines.append(f"- `{m.path}` ({m.change_velocity_30d} commits)")
        lines.append("")
        # Module purpose index
        lines.append("## Module Purpose Index")
        for m in sorted(modules.values(), key=lambda x: x.path)[:50]:
            purpose = m.purpose_statement or "(no purpose extracted)"
            lines.append(f"- `{m.path}`: {purpose[:80]}...")
        path.write_text("\n".join(lines), encoding="utf-8")

    def _write_onboarding_brief(self, path: Path, day_one_answers: Dict[str, DayOneAnswer]) -> None:
        lines: List[str] = [
            "# Onboarding Brief",
            "",
            "Day-One answers for FDE onboarding.",
            "",
        ]
        questions = [
            "What is the primary data ingestion path?",
            "What are the 3-5 most critical output datasets/endpoints?",
            "What is the blast radius if the most critical module fails?",
            "Where is business logic concentrated vs. distributed?",
            "What has changed most frequently in the last 90 days?",
        ]
        for q in questions:
            ans = day_one_answers.get(q)
            lines.append(f"## {q}")
            if ans:
                lines.append(ans.answer)
                if ans.evidence:
                    lines.append("")
                    lines.append("Evidence:")
                    for e in ans.evidence:
                        lines.append(f"- `{e.file}`:{e.line_range[0]}-{e.line_range[1]} ({e.analysis_method})")
            else:
                lines.append("(Answer not yet generated)")
            lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")

    def _write_lineage_graph(self, path: Path, graph: KnowledgeGraph) -> None:
        payload = graph.to_json()
        path.write_text(
            json.dumps(payload, indent=2, default=_serialize_default),
            encoding="utf-8",
        )

    def _append_trace(self, path: Path, traces: List[Dict[str, Any]]) -> None:
        with path.open("a", encoding="utf-8") as f:
            for event in traces:
                f.write(json.dumps(event, default=_serialize_default) + "\n")
